---
- name: "Check_certs | check if all certs have already been generated on first master"
  stat:
    path: "{{ etcd_cert_dir }}/{{ item }}"
  delegate_to: "{{groups['etcd'][0]}}"
  register: etcdcert_master
  run_once: true
  with_items: >-
       ['ca.pem',
       {% set all_etcd_hosts = groups['k8s-cluster']|union(groups['etcd'])|unique %}
       {% for host in all_etcd_hosts %}
       'node-{{ host }}-key.pem'
       {% if not loop.last %}{{','}}{% endif %}
       {% endfor %}]

- name: "Check_certs | Set default value for 'sync_certs' and 'etcd_gen_certs' to false"
  set_fact:
    sync_certs: false
    etcd_gen_certs: false

- name: "Check_certs | Set 'sync_certs' and 'etcd_gen_certs' to true"
  set_fact:
    gen_certs: true
  when: "not {{item.stat.exists}}"
  run_once: true
  with_items: "{{etcdcert_master.results}}"

- name: "Check certs | check if a cert already exists"
  stat:
    path: "{{ etcd_cert_dir }}/node-{{inventory_hostname}}.pem"
  register: etcdcert
  with_items:
    - ca.pem
    - node-{{ inventory_hostname }}.pem

- name: "Check_certs | Set 'sync_certs' to true"
  set_fact:
    sync_certs: true
  when: >-
      {%- set certs = {'sync': False} -%}
      {%- for server in play_hosts
         if (not hostvars[server].etcdcert.results[0].stat.exists|default(False)) or
         (hostvars[server].etcdcert.results[1].stat.checksum|default('') != etcdcert_master.results[1].stat.checksum|default('')) -%}
         {%- set _ = certs.update({'sync': True}) -%}
      {%- endfor -%}
      {{ certs.sync }}
  run_once: true
