---
- name: Set first kube master
  set_fact:
    first_kube_master: "{{ hostvars[groups['kube-master'][0]]['access_ip'] | default(hostvars[groups['kube-master'][0]]['ip'] | default(hostvars[groups['kube-master'][0]]['ansible_default_ipv4']['address'])) }}"

- name: Set external kube-apiserver endpoint
  set_fact:
    external_apiserver_endpoint: >-
      {%- if loadbalancer_apiserver is defined and loadbalancer_apiserver.port is defined -%}
      https://{{ apiserver_loadbalancer_domain_name|default('lb-apiserver.kubernetes.local') }}:{{ loadbalancer_apiserver.port|default(kube_apiserver_port) }}
      {%- else -%}
      https://{{ first_kube_master }}:{{ kube_apiserver_port }}
      {%- endif -%}
  tags: facts

- name: Gather kube cacert
  shell: cat {{ kube_cert_dir }}/ca.pem | base64 -w0
  delegate_to: "{{ groups['kube-master'][0] }}"
  delegate_facts: no
  register: kube_cacert

- name: Gather kube admin key
  shell: cat {{ kube_cert_dir }}/admin-{{ inventory_hostname }}-key.pem | base64 -w0
  delegate_to: "{{ groups['kube-master'][0] }}"
  delegate_facts: no
  register: kube_admin_key

- name: Gather kube admin cert
  shell: cat {{ kube_cert_dir }}/admin-{{ inventory_hostname }}.pem | base64 -w0
  delegate_to: "{{ groups['kube-master'][0] }}"
  delegate_facts: no
  register: kube_admin_cert

- name: Write admin kubeconfig
  template:
    src: admin.conf.j2
    dest: "{{ kube_config_dir }}/admin.conf"
  when: not kubeadm_enabled|d(false)|bool

- name: Create kube config dir
  file:
    path: "/root/.kube"
    mode: "0700"
    state: directory

- name: Copy admin kubeconfig to root user home
  copy:
    src: "{{ kube_config_dir }}/admin.conf"
    dest: "/root/.kube/config"
    remote_src: yes
    mode: "0700"
    backup: yes

- name: Copy admin kubeconfig and kubectl to ansible host
  fetch:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    flat: yes
    validate_checksum: no
  become: no
  run_once: yes
  when: kubeconfig_localhost|default(false)
  with_items:
    - {src: "{{ kube_config_dir }}/admin.conf", dest: "{{ artifacts_dir }}/admin.conf"}
    - {src: "{{ bin_dir }}/kubectl", dest: "{{ artifacts_dir }}/kubectl"}
