---
- name: Configure dhclient to prepend search/nameservers
  blockinfile:
    block: |-
      {% for item in [ prepend_search, prepend_nameserver ] -%}
      {{ item }}
      {% endfor %}
    dest: "{{dhclientconffile}}"
    create: yes
    state: present
    insertbefore: BOF
    backup: yes
    follow: yes
    marker: "# Ansible entries {mark}"
  notify: Dnsmasq | restart network

- name: Configue dhclient hooks for resolv.conf (non-RH)
  template:
    src: dhclient_dnsupdate.sh.j2
    dest: "{{ dhclienthookfile }}"
    owner: root
    mode: 0755
  notify: Dnsmasq | restart network
  when: ansible_os_family != "RedHat"

- name: Configue dhclient hooks for resolv.conf (RH-only)
  template:
    src: dhclient_dnsupdate_rh.sh.j2
    dest: "{{ dhclienthookfile }}"
    owner: root
    mode: 0755
  notify: Dnsmasq | restart network
  when: ansible_os_family == "RedHat"
